org: avinash360
app: serverless-express-todo-api
service: serverless-express-todo-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  environment:
    API_KEY: ${param:apiKey}
    AUTH_DOMAIN: ${param:authDomain}
    DATABASE_URL: ${param:databaseURL}
    PROJECT_ID: ${param:projectId}
    STORAGE_BUCKET: ${param:storageBucket}
    MESSAGING_SENDER_ID: ${param:messagingSenderId}
    APP_ID: ${param:appId}

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /tasks/{taskId}
          method: ANY
